name: android_minor
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper : any

  firebase_core: ^0.3.4
  firebase_storage: ^2.1.1+2
  firebase_auth: ^0.9.0
  firebase_database: ^2.0.3


  cloud_firestore: any
  shared_preferences: any

  camera: 0.4.0
  tflite: 1.0.4
  #google_maps_flutter: ^0.5.21+7
  cupertino_icons: ^0.1.2
  flushbar: ^1.9.0
  crypto: ^2.0.6
  intl: ^0.15.7
  outline_material_icons: ^0.1.0
  smart_text_view: ^0.1.0
  smooth_star_rating: ^1.0.1
  flutter_platform_widgets: ^0.9.5
  flutter_masked_text: 0.7.0
#  path_provider: any
  progress_dialog: ^1.0.7
  flutter_launcher_icons: ^0.6.1
  datetime_picker_formfield: ^0.1.8
  file_picker: ^1.3.7
  image_picker: ^0.6.1+4
  mime: ^0.9.6+3
  google_maps_flutter: ^0.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
